apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapidcompetitions
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rapidcompetitions
  template:
    metadata:
      labels:
        app: rapidcompetitions
    spec:
      containers:
        - name: rapidcompetitions
          image: younusfoysal/rapidcompetitions:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
