# Generated by Django 4.2 on 2024-06-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='sign_me_up',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='total_price',
        ),
    ]
