# Generated by Django 4.2 on 2024-06-05 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='Lottery/')),
                ('cash_alternative', models.IntegerField(blank=True, null=True)),
                ('draw_in', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('total_available_ticket', models.IntegerField()),
                ('total_sold', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lottery.category')),
            ],
        ),
    ]
