# Generated by Django 4.2 on 2024-06-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_lottery_max_entries_per_user_lotteryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
