# Generated by Django 4.2 on 2024-06-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0005_lottery_have_any_cash_alternative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='image',
            field=models.ImageField(upload_to='Competition/'),
        ),
    ]
