# Generated by Django 4.2 on 2024-06-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0006_alter_lottery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='have_any_cash_alternative',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'NO')], default='NO', max_length=80),
        ),
    ]
