# Generated by Django 4.2 on 2024-06-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0009_lottery_has_perform_draw_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='draw_by',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Auto')], default='AUTO', max_length=20),
        ),
    ]
