# Generated by Django 4.2 on 2024-06-16 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0010_lottery_draw_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lottery.lotteryticket'),
        ),
    ]
