# Generated by Django 4.2 on 2024-06-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0011_winner_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='lottery',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='user',
        ),
        migrations.DeleteModel(
            name='LotteryTicket',
        ),
        migrations.DeleteModel(
            name='Winner',
        ),
    ]
