# Generated by Django 4.2 on 2024-06-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0012_remove_winner_lottery_remove_winner_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='price_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
