# Generated by Django 4.2 on 2024-07-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0013_lottery_price_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='suggested_ticket_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
