# Generated by Django 4.2 on 2024-06-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_lotteryticket_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='winner_photo',
            field=models.ImageField(blank=True, null=True, upload_to='Winners/'),
        ),
    ]
